--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AID-LEARNING/mongo-php-library-virions
build-by-default: true
branches:
- master
projects:
  mongo-php-library-virions:
    path: ""
    model: virion
    type: library
...
